"""Create line-delimited manifests from AISHELL-1 without duplicating audio."""
from __future__ import annotations

import argparse
import json
import re
import wave
from pathlib import Path

from src.common import read_jsonl, write_jsonl


def normalize_text(text: str) -> str:
    return re.sub(r"\s+", "", re.sub(r"[^0-9A-Za-z\u4e00-\u9fff\s]", "", text)).strip()


def read_transcripts(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) == 2 and (text := normalize_text(parts[1])):
            result[parts[0]] = text
    return result


def duration_seconds(path: Path) -> float:
    with wave.open(str(path), "rb") as wav:
        return wav.getnframes() / wav.getframerate()


def build_manifests(root: Path, output_dir: Path) -> dict[str, int]:
    transcripts = read_transcripts(root / "transcript" / "aishell_transcript_v0.8.txt")
    mapping = {"train": "train", "dev": "validation", "test": "test"}
    counts: dict[str, int] = {}
    for source, target in mapping.items():
        rows = []
        for audio in sorted((root / "wav" / source).rglob("*.wav")):
            text = transcripts.get(audio.stem)
            if not text:
                continue
            seconds = duration_seconds(audio)
            if 1.0 <= seconds <= 30.0:
                rows.append({"audio_path": str(audio.resolve()), "text": text, "duration": seconds,
                             "speaker": audio.parent.name, "scene": "clean", "scene_label": 0})
        write_jsonl(rows, output_dir / f"{target}.jsonl")
        counts[target] = len(rows)
    return counts


def write_quality_report(output_dir: Path) -> None:
    """Record the exact manifest population used by downstream training."""
    report: dict[str, dict[str, float | int]] = {}
    for split in ("train", "validation", "test"):
        rows = read_jsonl(output_dir / f"{split}.jsonl")
        durations = [float(row["duration"]) for row in rows]
        report[split] = {
            "utterances": len(rows),
            "hours": round(sum(durations) / 3600, 3),
            "unique_speakers": len({row["speaker"] for row in rows}),
            "min_duration_seconds": round(min(durations), 3) if durations else 0,
            "max_duration_seconds": round(max(durations), 3) if durations else 0,
            "duplicate_audio_paths": len(rows) - len({row["audio_path"] for row in rows}),
        }
    (output_dir / "quality_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    card = ["# AISHELL-1 data card", "", "Generated by `src.data_prep`; audio is not copied.", "", "| Split | Utterances | Hours | Speakers | Duplicates |", "|---|---:|---:|---:|---:|"]
    for split, values in report.items():
        card.append(f"| {split} | {values['utterances']} | {values['hours']} | {values['unique_speakers']} | {values['duplicate_audio_paths']} |")
    (output_dir / "data_card.md").write_text("\n".join(card) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--aishell-root", type=Path, default=Path("data/raw/data_aishell"))
    parser.add_argument("--output-dir", type=Path, default=Path("data/processed/aishell1"))
    args = parser.parse_args()
    print(build_manifests(args.aishell_root, args.output_dir))
    write_quality_report(args.output_dir)


if __name__ == "__main__":
    main()
